spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question-service/**
          filters:
              - StripPrefix=1
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/quiz-service/**
          filters:
              - StripPrefix=1

server:
  port: 8090

eureka:
  instance:
    instance-id: api-gateway
    hostname: api-gateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 10